server:
  port: 9090

dubbo:
  application:
    name: stu
  registry:
    address: zookeeper://192.168.200.200:2181
  protocol:
    port: -1

spring:
  datasource:
    url: jdbc:mysql:///db_stu?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver