server:
  port: 9093

dubbo:
  application:
    name: classes
  registry:
    address: zookeeper://192.168.200.200:2181
  protocol:
    port: -1
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql:///db_cls?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver