server:
  port: 8081
dubbo:
  application:
    name: teacher-service
  registry:
    address: zookeeper://192.168.236.200:2181
  protocol:
    port: -1
  consumer:
    check: false

spring:
  datasource:
    url: jdbc:mysql:///db_teacher?serverTimezone=GMT%2B8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
